### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by lpar** [markleusink/XpageDebugToolbar#2]
There's no documentation for how to install the toolbar, and the OpenNTF project says "No documentation available".

**Comment by markleusink** [comment]
You're right :-(

I just added some documentation to the OpenNTF project site (http://www.openntf.org/main.nsf/project.xsp?r=project/XPage%20Debug%20Toolbar/documentation/066B7D652F14209886257CA800777C08).

Know that the Debug Toolbar is now:
- distributed as a plugin and should be installed accordingly (through an updatesite preferably).
- maintained in the OpenNTF GitHub repository (https://github.com/OpenNTF/DebugToolbar)

The project site on OpenNTF contains the latest release (currently 4.0.1). If you want a demo of it first, you can go here: https://demo.linqed.eu/debugtoolbar/debugtoolbar.nsf.
